[toolchain]
package_manager = "yarn"


[features]
resolution = true
skip-lint = false

[programs.localnet]
myproject = "BjerAfpSVqNzVgTQPgDMmQsR19MuMHoLGiR7LsMHWFU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
